--creation of database
create database sql_project1
--creating a table with column names
create table retail_sales1
(
transactions_id int PRIMARY KEY,
sale_date	date,
sale_time	time,
customer_id int, 
gender varchar(15),
age int,
category VARCHAR(15),
quantiy INT,
price_per_unit FLOAT,
cogs FLOAT,
total_sale FLOAT
);
--IDENTIFYING THE NULL VALUES IN TRANSACTION ID
SELECT*FROM retail_sales1
WHERE 
transactions_id IS NULL 
OR SALE_DATE IS NULL
OR SALE_TIME IS NULL
OR CUSTOMER_ID IS NULL
OR GENDER IS NULL
--OR AGE IS NULL
OR CATEGORY IS NULL
OR quantiy IS NULL
OR price_per_unit IS NULL
OR COGS IS NULL
OR TOTAL_SALE IS NULL
--DELETING THE NULL VALUES FROM TABLE.(DATA CLEANING PROCESS)
DELETE  FROM retail_sales1
WHERE 
transactions_id IS NULL 
OR SALE_DATE IS NULL
OR SALE_TIME IS NULL
OR CUSTOMER_ID IS NULL
OR GENDER IS NULL
--OR AGE IS NULL
OR CATEGORY IS NULL
OR quantiy IS NULL
OR price_per_unit IS NULL
OR COGS IS NULL
OR TOTAL_SALE IS NULL
--COUNTING THE ROWS IN A TABLE
SELECT 
COUNT(*) AS TOTAL_ROWS
FROM retail_sales1

--DATA EXPLORATION

--HOW MANY SALES WE HAVE OR CUSTOMERS.(1997)
SELECT
COUNT(*) FROM retail_sales1 

--CHECKING UNIQUE CUSTOMERS(155 CUSTOMERS)
SELECT 
DISTINCT(CUSTOMER_ID)
FROM retail_sales1

--CHECKING UNIQUE CATEGORIES (3-CLOTHING,ELECTRONICS,BEAUTY)
SELECT 
DISTINCT(category)
FROM retail_sales1

--DATA ANALYSIS & BUSSINESS KEY PROBLEMS & ANSWERS

-- WRITE A SQL QUERY TO RETRIVE ALL COLUMNS FOR SALES MADE ON '2022-11-05'
SELECT *FROM retail_sales1
WHERE SALE_DATE='2022-11-05'

--WRITE A SQL QUERY TO RETRIVE ALL TRANSACTIONS WHERE THE CATEGORY IS 'CLOTHING'
--AND THE QUANTITY SOLD IS MORE THAN 10 IN THE MONTH OF NOV-2022.

SELECT * FROM retail_sales1
WHERE CATEGORY='CLOTHING'
AND quantiy>3
AND SALE_DATE >='2022-11-01'
AND SALE_DATE<'2022-12-01'

--WRITE A SQL QUERY TO CALCULATE THE TOTAL SALESFOR EACH CATEGORY
SELECT
CATEGORY,
COUNT(*)AS TOTAL_COUNT,
SUM(TOTAL_SALE) AS TOTAL_SALES_FOR_EACHCATEGORY
FROM retail_sales1
GROUP BY category

--WRITE A SQL QUERY TO FIND THE AVERAGE AGE OF CUSTOMERSS WHO PURCHASED ITEMS FROM THE 'BEAUTY' CATEGORY
SELECT
AVG(AGE) AS AVERAGE_AGE,
CATEGORY
FROM retail_sales1
WHERE CATEGORY='BEAUTY'
GROUP BY CATEGORY

--WRITE A SQL QUERY TO FIND ALL TRANSACTIONS WHERE TOTAL_SALE IS GRATER THAN 1000.
SELECT*FROM retail_sales1
WHERE TOTAL_SALE>1000

--WRITE A SQL QUERY TO FIND TOTAL NO.OF TRANSCATIONS(TRANSACTION_ID) MADE BY EACH GENDER IN EACH CATEGORY.

SELECT
COUNT(TRANSACTIONS_ID)AS TOTAL_TRANSACTIONS,
GENDER,
CATEGORY
FROM retail_sales1
GROUP BY GENDER,CATEGORY

--WRITE A SQL QUERY TO CALCULATE THE AVERAGE SALEE FOR EACH MONTH.FIND OUT BEST SELLING MONTH IN EACH YEAR.
SELECT*FROM(
SELECT
AVG(TOTAL_SALE)AS AVGSALE,
DATEPART(MONTH,SALE_DATE)AS MONTH_SALE,
DATEPART(YEAR,SALE_DATE)AS YEAR_SALE,
RANK()OVER(PARTITION BY DATEPART(YEAR,SALE_DATE)ORDER BY AVG(TOTAL_SALE) DESC)AS RANK
FROM retail_sales1
GROUP BY DATEPART(MONTH,SALE_DATE),DATEPART(YEAR,SALE_DATE))
--ORDER BY DATEPART(YEAR,SALE_DATE),AVG(TOTAL_SALE) DESC)
AS T1
WHERE RANK=1

--FIND THE TOP 5 CUSTOMERS BASED ON THE HIGHEST TOTAL_SALES
SELECT*FROM retail_sales1
SELECT TOP(5)
CUSTOMER_ID,
SUM(TOTAL_SALE)AS TOTAL_sALES
FROM retail_sales1
GROUP BY customer_id
ORDER BY TOTAL_sALES DESC

--WRITE A SQL QUERY TO FIND THE NUMBER OF UNIQUE CUSTOMERS WHO PURCHASED ITEMS FROM EACH CATEGORY.
SELECT
COUNT(DISTINCT(CUSTOMER_ID))AS CUSTOMERS,
CATEGORY
FROM retail_sales1
GROUP BY CATEGORY

--WRITE A SQL QUERY TO CREATE EACH SHIFT AND NUMBER OF ORDERS
--(EXAMPLE MORNING<=12,AFTERNOON BETWEEN 12&17,EVENING>17)
SELECT*FROM retail_sales1

WITH HOURLY_SALE
AS
(SELECT
*,
CASE
	WHEN DATEPART(HOUR,SALE_TIME)<12 THEN 'MORNING'
	WHEN DATEPART(HOUR,SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
ELSE
'EVENING'
END AS SHIFT
FROM retail_sales1)
SELECT
SHIFT,
COUNT(*)AS TOTAL_ORDERS
FROM HOURLY_SALE
GROUP BY SHIFT


